#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=99

USE_PROCD=1

start_service() {
	[ -d /var/log/nginx ] || mkdir -p /var/log/nginx
	[ -d /var/lib/nginx ] || mkdir -p /var/lib/nginx

	procd_open_instance
	procd_set_param command /usr/sbin/nginx -c /home/www-data/nginx-rest.conf -g 'daemon off;'
	procd_set_param file /home/www-data/nginx-rest.conf
	procd_set_param respawn 0 5 0
	procd_close_instance
}
